version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - PORT=3000
      - PROD=false
      - JWT_SECRET=jwt123
      - JWT_SECRET_REFRESH=jwt_refresh_123
      - ACCESS_TOKEN_EXPIRATION_SECONDS=3600
      - REFRESH_TOKEN_EXPIRATION_SECONDS=2592000
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
